In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Preprocessing


In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# test and train split

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# ANN

In [0]:
ann = tf.keras.models.Sequential()

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compile

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training

In [15]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5305 - accuracy: 0.7906
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4719 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4522 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4377 - accuracy: 0.7987
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4293 - accuracy: 0.8091
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4242 - accuracy: 0.8152
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4199 - accuracy: 0.8188
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4154 - accuracy: 0.8217
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4110 - accuracy: 0.8254
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4067 - accura

In [16]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]
